start: "2024-09-01T00:00:00Z"

variables:
  malware_family: "TrickBot"
  infection_id: "INF-9847"

actors:
  - name: malware
    base: users/alice/AppData/Local/Temp
    variables:
      c2_ip: "198.51.100.42"

  - name: persistence
    base: users/alice/AppData/Roaming

  - name: lateral
    base: C/Windows/Temp

steps:
  # Initial dropper execution
  - actor: malware
    offset: 0s
    actions:
      - action: create
        path: ${RND:8}.exe
        content_len: 4096
      - action: ads
        path: ${RND:8}.exe
        stream: Zone.Identifier
        content: "[ZoneTransfer]\r\nZoneId=3\r\n"

  # Beacon establishment
  - actor: malware
    offset: 30s
    every: 60s
    repeat: 100
    actions:
      - action: append
        path: .beacon.log
        content: "${DATE:2006-01-02T15:04:05Z07:00} BEACON id=${VAR:infection_id} c2=${VAR:c2_ip} status=OK jitter=${HASH:4}\n"

  # Registry persistence artifacts (file-based)
  - actor: persistence
    offset: 2m
    actions:
      - action: create
        path: Microsoft/Windows/Start Menu/Programs/Startup/WindowsUpdate.lnk
        content_len: 256
        mtime: "2024-08-15T10:00:00Z"
      - action: create
        path: .persistence.reg
        content: |
          Windows Registry Editor Version 5.00

          [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run]
          "SystemUpdate"="C:\\Users\\alice\\AppData\\Local\\Temp\\${RND:8}.exe"

  # Credential harvesting simulation
  - actor: malware
    offset: 5m
    batch_count: 5
    actions:
      - action: create
        path: creds-${BATCH}.txt
        content: |
          ${VAR:malware_family} Credential Dump
          Timestamp: ${DATE:2006-01-02T15:04:05Z07:00}
          User: alice
          Hash: ${HASH:32}
          Domain: WORKGROUP

  # Lateral movement artifacts
  - actor: lateral
    offset: 10m
    repeat: 3
    every: 5m
    batch_count: 2
    actions:
      - action: create
        path: scan-${ITER}-${BATCH}.tmp
        template: log
      - action: create
        path: smb-${IP}.tmp
        content_len: 512
        condition: even

  # Data reconnaissance
  - actor: malware
    offset: 20m
    repeat: 10
    every: 2m
    actions:
      - action: create
        path: enum-${SEQ}.txt
        content: "Directory listing - ${DATE:2006-01-02T15:04:05Z07:00}\nFiles: ${HASH:64}\n"
      - action: append
        path: recon.log
        content: "${DATE:2006-01-02T15:04:05Z07:00} SCAN path=Documents depth=3 files=${HASH:4}\n"

  # Staged data collection
  - actor: malware
    offset: 45m
    batch_count: 30
    actions:
      - action: create
        path: stage/${BATCH}.dat
        content_len: 8192
      - action: create
        path: stage/chunk-${UUID}.enc
        content_len: 4096
        condition: odd

  # Exfiltration preparation
  - actor: malware
    offset: 1h
    actions:
      - action: create
        path: exfil-ready.zip
        content_len: 262144
      - action: ads
        path: exfil-ready.zip
        stream: metadata
        content: "campaign=${VAR:infection_id}\ntarget=alice\nsize=256KB\n"

  # C2 communication logs
  - actor: malware
    offset: 1h10m
    every: 30s
    repeat: 50
    actions:
      - action: append
        path: c2.log
        content: "${DATE:2006-01-02T15:04:05Z07:00} C2 cmd=EXFIL chunk=${SEQ} size=${HASH:6} dst=${VAR:c2_ip}:443\n"

  # Self-propagation attempts
  - actor: lateral
    offset: 1h30m
    batch_count: 5
    actions:
      - action: create
        path: worm-${BATCH}.exe
        content_len: 4096
      - action: create
        path: spread-${IP}.log
        template: log

  # Anti-forensics - log manipulation
  - actor: malware
    offset: 2h
    actions:
      - action: truncate
        path: .beacon.log
      - action: delete
        path: creds-0.txt
      - action: delete
        path: creds-1.txt
      - action: delete
        path: recon.log
      - action: mace
        path: stage
        mtime: "2024-01-01T00:00:00Z"

  # Persistence check (later)
  - actor: persistence
    offset: 24h
    actions:
      - action: create
        path: .health-check
        content: "${VAR:malware_family} alive - ${DATE:2006-01-02T15:04:05Z07:00}\n"
      - action: append
        path: ../Local/Temp/.beacon.log
        content: "${DATE:2006-01-02T15:04:05Z07:00} PERSISTENCE verified id=${VAR:infection_id}\n"

  # Ransomware deployment (if enabled)
  - actor: malware
    offset: 48h
    batch_count: 100
    condition: even
    actions:
      - action: create
        path: ../../Documents/file-${BATCH}.docx.locked
        content_len: 2048
      - action: create
        path: ../../Pictures/photo-${BATCH}.jpg.locked
        content_len: 1024

  # Final ransom note
  - actor: malware
    offset: 48h5m
    actions:
      - action: create
        path: ../../Desktop/DECRYPT_INSTRUCTIONS.txt
        content: |
          YOUR FILES HAVE BEEN ENCRYPTED BY ${VAR:malware_family}

          Infection ID: ${VAR:infection_id}
          Encrypted: ${DATE:2006-01-02T15:04:05Z07:00}

          Your unique decryption key: ${UUID}

          To recover files, send 1 BTC to:
          ${HASH:64}

          After payment, contact: ${VAR:c2_ip}
